query Maraudes {
  maraudes {
    id
    nomGroupe
    personnes {
        id
        nom
        prenom
    }
    maraudeTerminee
    trajet{
      	id
      	lieuDepart
      	lieuArrivee
    }
  }
}
